unzip("exdata_data_household_power_consumption.zip")
energydata <- read.table("household_power_consumption.txt",header=TRUE, na.string="?",sep=";",stringsAsFactor=FALSE)
energydata[,1] <- as.Date(energydata[,1],format="%d/%m/%Y")
plotdata <- subset(energydata,Date=="2007-02-01"|Date=="2007-02-02")
colnames(plotdata)<-make.names(colnames(plotdata))
colnames(plotdata)<-tolower(colnames(plotdata))
plotdata <- transform(plotdata, time=paste(date,time))
plotdata <- transform(plotdata1, time=strptime(time,"%Y-%m-%d %H:%M:%S"))
png("plot4.png",width=480,height=480)
par(mfcol=c(2,2))
plot(plotdata$time,plotdata$global_active_power,ylab="Global Active Power (kilowatts)",xlab="",type="n")
lines(plotdata$time,plotdata$global_active_power,type="l")
plot(plotdata$time,plotdata$sub_metering_1,ylab="Energy sub metering",xlab="",type="n")
lines(plotdata$time,plotdata$sub_metering_1,type="l")
lines(plotdata$time,plotdata$sub_metering_2,type="l",col="red")
lines(plotdata$time,plotdata$sub_metering_3,type="l",col="blue")
legend("topright",cex=0.75, bty="n",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1))
with(plotdata,{
  plot(time,voltage,xlab="datetime",ylab="Voltage",type="n")
  lines(time,voltage,type="l")
  plot(time,global_reactive_power,xlab="datetime",ylab="Global_reactive_power",type="n")
  lines(time,global_reactive_power,type="l")  
})
dev.off()