unzip("exdata_data_household_power_consumption.zip")
energydata <- read.table("household_power_consumption.txt",header=TRUE, na.string="?",sep=";",stringsAsFactor=FALSE)
energydata[,1] <- as.Date(energydata[,1],format="%d/%m/%Y")
plotdata <- subset(energydata,Date=="2007-02-01"|Date=="2007-02-02")
colnames(plotdata)<-make.names(colnames(plotdata))
colnames(plotdata)<-tolower(colnames(plotdata))
plotdata <- transform(plotdata, time=paste(date,time))
plotdata <- transform(plotdata1, time=strptime(time,"%Y-%m-%d %H:%M:%S"))
png("plot2.png",width=480,height=480)
plot(plotdata$time,plotdata$global_active_power,ylab="Global Active Power (kilowatts)",xlab="",type="n")
lines(plotdata$time,plotdata$global_active_power,type="l")
dev.off()