unzip("exdata_data_household_power_consumption.zip")
energydata <- read.table("household_power_consumption.txt",header=TRUE, na.string="?",sep=";",stringsAsFactor=FALSE)
energydata[,1] <- as.Date(energydata[,1],format="%d/%m/%Y")
#try <- strptime(energydata[,2],format ="%H:%M:%S")
plotdata <- subset(energydata,Date=="2007-02-01"|Date=="2007-02-02")
names(plotdata)<-make.names(names(plotdata))
names(plotdata)<-tolower(names(plotdata))
png("plot1.png",width=480,height=480)
hist(plotdata$global_active_power,col="red",xlab="Global Active Power (kilowatts)",main="Global Active Power")
dev.off()